### PR TITLE
Be less restrictive on the rubocop  version required.

### PR DESCRIPTION
**Pull request by franciscoj**
`~> 0.41.0` is too restrictive. Will only work with `0.41.x` and will basically require this to be updated on each new rubocop release. `~> 0.41` grants us dependency sanity on `0.x.y`.

### CODE REVIEW

**Comment by enricostano** [comment]
I expect `0.42` to break this

**Comment by franciscoj** [comment]
Then we can fix it when it is broken. Requiring a new release on each new version is a pain. Even more when this is non critical piece anywhere and with the restriction we are only making it harder to use.

**Comment by franciscoj** [comment]
In addition I checked and it works with `0.42.x` and with `0.43` which is the latest version.

**Comment by enricostano** [comment]
:+1:

**Pull request merged**
